# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('_fast_lasso_rcppeigen_hello_world', PACKAGE = 'fast.lasso')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_fast_lasso_rcppeigen_outerproduct', PACKAGE = 'fast.lasso', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_fast_lasso_rcppeigen_innerproduct', PACKAGE = 'fast.lasso', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_fast_lasso_rcppeigen_bothproducts', PACKAGE = 'fast.lasso', x)
}

fast_lasso_sum_ess <- function(bVec, sVec, r2Mat, n, group, lambda, alpha) {
    .Call('_fast_lasso_fast_lasso_sum_ess', PACKAGE = 'fast.lasso', bVec, sVec, r2Mat, n, group, lambda, alpha)
}

